# Generated by Django 4.2.8 on 2024-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='img',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(default='Bilgi yok', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SoyAd'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
    ]
